version: "3"

services:
  mysql:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
